export const copy = {
  EN: {
    navHome: 'Home', navProducts: 'Products', navServices: 'Engineering Services',
    navIndustries: 'Industries', navPortal: 'B2B Portal',
    heroTagA: 'DRIVETRAIN RELIABILITY PARTNER — SINCE 2002',
    heroH1A: 'Engineering\nSolutions That\nKeep Industry\nMoving.',
    heroSubA: 'Industrial power transmission — chains, sprockets, drives, and certified vibration diagnostics for Indonesia’s critical industries.',
    heroCTA1: 'Book Free Vibration Audit',
    heroCTA2: 'Download Product Catalog',
    heroTagB: 'EST. 2002 · JAKARTA · INDONESIA',
    heroH1B: 'Your Drivetrain\nReliability\nPartner.',
    heroSubB: 'From Prima Chain to custom MTO pulleys — we engineer solutions, not just sell parts.',
    stat1Val: '20+', stat1Lab: 'Years Expertise',
    stat2Val: '500+', stat2Lab: 'Clients Served',
    stat3Val: 'MTO', stat3Lab: 'Custom Engineering',
    stat4Val: 'FREE', stat4Lab: 'On-Site Audit',
    servicesTitle: 'Engineering Services',
    servicesSub: 'Certified diagnostics that open doors to high-margin MTO solutions.',
    productsTitle: 'Our Product Portfolio',
    productsSub: 'Complete drivetrain solutions under one roof.',
    industriesTitle: 'Industries We Serve',
    industriesSub: "Deep domain knowledge across Indonesia's critical sectors.",
    trustTitle: 'Proven Results',
    trustSub: 'Real data from real deployments.',
    auditTitle: 'Book a Free Vibration Audit',
    auditSub: 'Our SKF Microlog-certified engineers diagnose your machinery — at no cost. This is the first step to identifying MTO solutions that reduce downtime.',
    footerDesc: 'Industrial drivetrain solutions and certified engineering diagnostics since 2002.',
    footerProducts: 'Products',
    footerServices: 'Services',
    footerContact: 'Contact',
    bundle: 'Frequently Bought Together',
    viewAll: 'View All Products',
    learnMore: 'Learn More'
  },
  ID: {
    navHome: 'Beranda', navProducts: 'Produk', navServices: 'Layanan Engineering',
    navIndustries: 'Industri', navPortal: 'Portal B2B',
    heroTagA: 'MITRA KEANDALAN DRIVETRAIN — SEJAK 2002',
    heroH1A: 'Solusi Engineering\nyang Menjaga\nIndustri Terus\nBergerak.',
    heroSubA: 'Transmisi daya industri — rantai, sproket, drive, dan diagnostik vibrasi bersertifikat untuk industri kritis Indonesia.',
    heroCTA1: 'Pesan Audit Vibrasi Gratis',
    heroCTA2: 'Unduh Katalog Produk',
    heroTagB: 'BERDIRI 2002 · JAKARTA · INDONESIA',
    heroH1B: 'Mitra Keandalan\nDrivetrain\nAnda.',
    heroSubB: 'Dari Rantai Prima hingga pulley MTO kustom — kami memberikan solusi engineering, bukan sekadar menjual suku cadang.',
    stat1Val: '20+', stat1Lab: 'Tahun Pengalaman',
    stat2Val: '500+', stat2Lab: 'Klien Dilayani',
    stat3Val: 'MTO', stat3Lab: 'Rekayasa Kustom',
    stat4Val: 'GRATIS', stat4Lab: 'Audit On-Site',
    servicesTitle: 'Layanan Engineering',
    servicesSub: 'Diagnostik bersertifikat yang membuka peluang solusi MTO margin tinggi.',
    productsTitle: 'Portofolio Produk Kami',
    productsSub: 'Solusi drivetrain lengkap dalam satu atap.',
    industriesTitle: 'Industri yang Kami Layani',
    industriesSub: 'Pengetahuan mendalam di sektor-sektor kritis Indonesia.',
    trustTitle: 'Hasil Terbukti',
    trustSub: 'Data nyata dari implementasi nyata.',
    auditTitle: 'Pesan Audit Vibrasi Gratis',
    auditSub: 'Engineer bersertifikat SKF Microlog kami mendiagnosis mesin Anda — tanpa biaya. Ini adalah langkah pertama untuk mengidentifikasi solusi MTO yang mengurangi downtime.',
    footerDesc: 'Solusi drivetrain industri dan diagnostik engineering bersertifikat sejak 2002.',
    footerProducts: 'Produk',
    footerServices: 'Layanan',
    footerContact: 'Kontak',
    bundle: 'Sering Dibeli Bersama',
    viewAll: 'Lihat Semua Produk',
    learnMore: 'Pelajari Lebih Lanjut'
  }
};
